name: Deploy Flask app

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  build:
    name: build the deployment artifacts
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: compress files into tar.gz artifact
        run: |
          mkdir -p ../deploy
          cp -r . ../deploy
          tar -czf flask_app.tar.gz -C ../deploy .
                  
      - name: Deploy to dev server
        if: github.ref == 'refs/heads/dev'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          SERVER: ${{ secrets.DEV_SERVER }}
          USER: ${{ secrets.DEV_USER}}
        run: |
          echo "**RUNNING DEV BRANCH DEPLOYMENT**"
          echo $SERVER

          
        continue-on-error: false
