name: Deploy Flask app

on:
  push:
    branches:
      - main
      - dev
      - test

jobs:
  build:
    name: build the deployment artifacts
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: compress files into tar.gz artifact
        run: |
          mkdir -p ../deploy
          cp -r . ../deploy
          tar -czf flask_app.tar.gz -C ../deploy .
                  
      - name: Deploy artifact through ssh
        uses: appleboy/ssh-action@v1.0.3
        if: github.ref == 'refs/heads/dev'
        with:
          host: ${{ secrets.DEV_SERVER }}
          username: ${{ secrets.DEV_USER}}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script_stop: true
          debug: true
          script: |
            echo "**RUNNING DEV BRANCH DEPLOYMENT**"
            pid=$(lsof -ti tcp:8080)
            if [[ $pid ]]; then
              echo "**Terminating Flask**"
              kill -9 $pid
            else
              echo "**Flask was not running**"
            fi
        continue-on-error: false
